# Generated by Django 5.2.7 on 2025-11-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('chat_id', models.CharField(max_length=30, unique=True)),
                ('appointment1_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora 1ª Consulta')),
                ('appointment1_gcal_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Google Calendar 1')),
                ('appointment2_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora 2ª Consulta')),
                ('appointment2_gcal_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Google Calendar 2')),
            ],
        ),
    ]
