# Generated by Django 5.2.7 on 2025-12-01 21:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMetrica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_id', models.CharField(db_index=True, help_text='ID do cliente (telefone ou UUID)', max_length=50)),
                ('event_id', models.CharField(db_index=True, help_text='ID do evento no calendário', max_length=100)),
                ('tipo_metrica', models.CharField(choices=[('agendamento', 'Agendamento'), ('cancelamento', 'Cancelamento'), ('lembrete', 'Lembrete Enviado')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('failed', 'Falha'), ('pending', 'Pendente')], default='success', max_length=10)),
                ('detalhes', models.TextField(blank=True, help_text='Informações adicionais do evento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Log de Métrica',
                'verbose_name_plural': 'Logs de Métricas',
                'db_table': 'logs_metricas',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['cliente_id', 'criado_em'], name='logs_metric_cliente_f044de_idx'), models.Index(fields=['tipo_metrica', 'criado_em'], name='logs_metric_tipo_me_90918b_idx'), models.Index(fields=['event_id'], name='logs_metric_event_i_efe452_idx'), models.Index(fields=['criado_em'], name='logs_metric_criado__6d1c4e_idx')],
            },
        ),
    ]
